-- local osc52 = require("vim.ui.clipboard.osc52")
--
-- vim.g.clipboard = {
--   name = "OSC52",
--   copy = {
--     ["+"] = osc52.copy("+"),
--     ["*"] = osc52.copy("*"),
--   },
--   paste = {
--     ["+"] = function()
--       return vim.split(vim.fn.getreg("+"), "\n"), vim.fn.getregtype("+")
--     end,
--     ["*"] = function()
--       return vim.split(vim.fn.getreg("*"), "\n"), vim.fn.getregtype("*")
--     end,
--   },
-- }
--
-- vim.opt.clipboard = "unnamedplus"
