# autogenerated by txs
\DH#S
\DJ#S
\NG#S
\TH#S
\dh#S
\dj#S
\filedate#S
\fileversion#S
\guillemotleft#S
\guillemotright#S
\guilsinglleft#S
\guilsinglright#S
\ng#S
\textpertenthousand#S
\textperthousand#S
\th#S
