-- vim.o.completeopt = "menuone,noselect"
-- require'compe'.setup {
--   enabled = true;
--   autocomplete = true;
--   debug = false;
--   min_length = 2;
--   preselect = 'enable';
--   throttle_time = 10;
--   source_timeout = 200;
--   incomplete_delay = 400;
--   max_abbr_width = 80;
--   max_kind_width = 10;
--   max_menu_width = 10;
--   documentation = false;

--   source = {
--     path = true;
--     buffer = true;
--     calc = false;
--     vsnip = false;
--     nvim_lsp = true;
--     nvim_lua = true;
--     spell = false;
--     tags = false;
--     snippets_nvim = false;
--     treesitter = true;
--     ultisnips = true;
--   };
-- }
