export XDG_CONFIG_HOME="/Users/wangk/.config/"
# using Exuberant ctags
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
# using cargo
export PATH="/Users/wangk/.cargo/bin:$PATH"
# go package
export PATH="/Users/wangk/go/bin:$PATH"
# config node_module path
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
# add my package path
export PYTHONPATH="$PYTHONPATH:/Users/wangk/anaconda3/lib/python3.9/site-packages/"
export PYTHONPATH="$PYTHONPATH:/Users/wangk/MyLibrary/libsource/"
export PYTHONPATH="$PYTHONPATH:/Users/wangk/MyLibrary/enhanced/"
# for the correctly running of cython compile
export CFLAGS="-I /Users/wangk/anaconda3/lib/python3.9/site-packages/numpy/core/include $CFLAGS"
# for zathura in vimtex, see *vimtex-faq-zathura-macos* in vimtex document
export DBUS_SESSION_BUS_ADDRESS="unix:path=$DBUS_LAUNCHD_SESSION_BUS_SOCKET"
# MacPorts Installer addition on 2017-09-06_at_21:58:33: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# limit the threads of numpy lib
# export MKL_NUM_THREADS=1
# export NUMEXPR_NUM_THREADS=1
# export OMP_NUM_THREADS=1
# toggle true color
export TERM="xterm-256color"
# high light the mannul
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;38;5;74m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[38;5;;246m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[04;38;5;146m'
# better exceptions
export BETTER_EXCEPTIONS=1
# useful export
export EDITOR='nvim'
export CC='/opt/homebrew/bin/g++-12'

# alias
export MYLIB_PATH=/Users/wangk/MyLibrary
# path
export PATH=$MYLIB_PATH/bin:$PATH
export PATH=$MYLIB_PATH/libsource/hdf/HDF_Group/HDF5/1.12.1/bin:$PATH
# local package
export C_INCLUDE_PATH=/usr/local/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/usr/local/include/:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
export LIBRARY_PATH=/usr/local/lib/:$LIBRARY_PATH
# My library
export C_INCLUDE_PATH=$MYLIB_PATH/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/include/:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=$MYLIB_PATH/lib/:$LD_LIBRARY_PATH
export LIBRARY_PATH=$MYLIB_PATH/lib/:$LIBRARY_PATH
# gsl
export C_INCLUDE_PATH=$MYLIB_PATH/include/gsl/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/include/gsl/:$CPLUS_INCLUDE_PATH
# yaml-cpp path
export C_INCLUDE_PATH=$MYLIB_PATH/libsource/yaml-cpp/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/libsource/yaml-cpp/include/:$CPLUS_INCLUDE_PATH
# hdf5
export C_INCLUDE_PATH=$MYLIB_PATH/include/hdf5/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/include/hdf5/:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=$MYLIB_PATH/lib/hdf5/:$LD_LIBRARY_PATH
export LIBRARY_PATH=$MYLIB_PATH/lib/hdf5/:$LIBRARY_PATH
# hipp
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/libsource/hipp/include/:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=$MYLIB_PATH/libsource/hipp/lib/:$LD_LIBRARY_PATH
export LIBRARY_PATH=$MYLIB_PATH/libsource/hipp/lib/:$LIBRARY_PATH
export LD_RUNPATH_SEARCH_PATH=$MYLIB_PATH/libsource/hipp/lib/:$LD_RUNPATH_SEARCH_PATH
# boost
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/libsource/boost_1_80_0/:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=$MYLIB_PATH/libsource/boost_1_80_0/:$LIBRARY_PATH
# npm access problem, see https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
export PATH=~/.npm-global/bin:$PATH
# for eigen
export CPLUS_INCLUDE_PATH=/usr/local/include/eigen3/:$CPLUS_INCLUDE_PATH
# for boost
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/libsource/boost_1_79_0/:$CPLUS_INCLUDE_PATH
# HIPP
HIPP_PATH=/Users/wangk/MyLibrary/libsource/hipp/install/
export CPLUS_INCLUDE_PATH=$HIPP_PATH/include/:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=$HIPP_PATH/lib/:$LIBRARY_PATH
export DL_LIBRARY_PATH=$HIPP_PATH/lib/:$DL_LIBRARY_PATH
