export XDG_CONFIG_HOME="/Users/wangk/.config/"
# using Exuberant ctags
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
# using cargo
export PATH="/Users/wangk/.cargo/bin:$PATH"
# go package
export PATH="/Users/wangk/go/bin:$PATH"
# config node_module path
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
# add my package path
export PYTHONPATH="$PYTHONPATH:/Users/wangk/anaconda3/lib/python3.11/site-packages/"
export PYTHONPATH="$PYTHONPATH:/Users/wangk/MyLibrary/libsource/"
export PYTHONPATH="$PYTHONPATH:/Users/wangk/MyLibrary/enhanced/"
export PYTHONPATH="$PYTHONPATH:/Users/wangk/MyLibrary/libsource/SatGen/"
# for the correctly running of cython compile
export CFLAGS="-I /Users/wangk/anaconda3/lib/python3.11/site-packages/numpy/core/include $CFLAGS"
# for zathura in vimtex, see *vimtex-faq-zathura-macos* in vimtex document
export DBUS_SESSION_BUS_ADDRESS="unix:path=$DBUS_LAUNCHD_SESSION_BUS_SOCKET"
# toggle true color
export TERM="xterm-256color"
# high light the mannul
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;38;5;74m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[38;5;;246m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[04;38;5;146m'
# better exceptions
export BETTER_EXCEPTIONS=1
# useful export
export EDITOR='nvim'
export CC='/opt/homebrew/bin/g++-13'

# alias
export MYLIB_PATH=/Users/wangk/MyLibrary
# local package
export PATH=$MYLIB_PATH/bin:$PATH
export C_INCLUDE_PATH=/usr/local/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/usr/local/include/:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
export LIBRARY_PATH=/usr/local/lib/:$LIBRARY_PATH
# yaml-cpp path
export C_INCLUDE_PATH=$MYLIB_PATH/libsource/yaml-cpp/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/libsource/yaml-cpp/include/:$CPLUS_INCLUDE_PATH
# boost
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/libsource/boost_1_80_0/:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=$MYLIB_PATH/libsource/boost_1_80_0/:$LIBRARY_PATH
# eigen
export CPLUS_INCLUDE_PATH=/usr/local/include/eigen3/:$CPLUS_INCLUDE_PATH
# libevent
export PATH=$MYLIB_PATH/libevent/bin/:$PATH
export C_INCLUDE_PATH=$MYLIB_PATH/libevent/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/libevent/include/:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=$MYLIB_PATH/libevent/lib/:$LD_LIBRARY_PATH
export LIBRARY_PATH=$MYLIB_PATH/libevent/lib/:$LIBRARY_PATH
# openmpi
export PATH=$MYLIB_PATH/openmpi/bin/:$PATH
export C_INCLUDE_PATH=$MYLIB_PATH/openmpi/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/openmpi/include/:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=$MYLIB_PATH/openmpi/lib/:$LD_LIBRARY_PATH
export LIBRARY_PATH=$MYLIB_PATH/openmpi/lib/:$LIBRARY_PATH
# gsl
export PATH=$MYLIB_PATH/gsl/bin/:$PATH
export C_INCLUDE_PATH=$MYLIB_PATH/gsl/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/gsl/include/:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=$MYLIB_PATH/gsl/lib/:$LD_LIBRARY_PATH
export LIBRARY_PATH=$MYLIB_PATH/gsl/lib/:$LIBRARY_PATH
# fftw3
export PATH=$MYLIB_PATH/fftw3/bin/:$PATH
export C_INCLUDE_PATH=$MYLIB_PATH/fftw3/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/fftw3/include/:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=$MYLIB_PATH/fftw3/lib/:$LD_LIBRARY_PATH
export LIBRARY_PATH=$MYLIB_PATH/fftw3/lib/:$LIBRARY_PATH
# hdf5
export PATH=$MYLIB_PATH/hdf5/bin/:$PATH
export C_INCLUDE_PATH=$MYLIB_PATH/hdf5/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/hdf5/include/:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=$MYLIB_PATH/hdf5/lib/:$LD_LIBRARY_PATH
export LIBRARY_PATH=$MYLIB_PATH/hdf5/lib/:$LIBRARY_PATH
# hwloc
export PATH=$MYLIB_PATH/hwloc/bin/:$PATH
export C_INCLUDE_PATH=$MYLIB_PATH/hwloc/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/hwloc/include/:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=$MYLIB_PATH/hwloc/lib/:$LD_LIBRARY_PATH
export LIBRARY_PATH=$MYLIB_PATH/hwloc/lib/:$LIBRARY_PATH
# hipp
export C_INCLUDE_PATH=$MYLIB_PATH/package/hipp/include/:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$MYLIB_PATH/package/hipp/include/:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=$MYLIB_PATH/package/hipp/lib/:$LD_LIBRARY_PATH
export LIBRARY_PATH=$MYLIB_PATH/package/hipp/lib/:$LIBRARY_PATH
# FSPS
export SPS_HOME=/Users/wangk/MyLibrary/libsource/fsps/

# npm access problem, see https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
export PATH=~/.npm-global/bin:$PATH
